name: CI/CD - Python API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clona o repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2️⃣ Configura o Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # ajuste conforme sua versão

      # 3️⃣ Instala dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Gera relatório de cobertura (opcional)
      - name: Gerar relatório de cobertura
        run: |
          pip install coverage
          coverage run -m pytest
          coverage report
          coverage xml

      - name: Build e push Docker
        run: |
          docker build -t usuario/carteira-na-mao:latest .
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u usuario --password-stdin
          docker push usuario/carteira-na-mao:latest